apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-projects-claim-efs
  namespace: awx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi